version: '3.8'

services:
  recruta-app:
    build: .
    container_name: recruta_ai_app
    restart: unless-stopped
    ports:
      - "3456:3456"
    env_file:
      - .env
    volumes:
      - recruta_data:/app/server/storage/data
    networks:
      - recruta_net

volumes:
  recruta_data:

networks:
  recruta_net:
    driver: bridge